stages:
  - build

devclient:
  stage: build
  tags:
    - ubuntu

  script:
    - mkdir build && cd build
    - cmake ..
    - make all
    - make package
  artifacts:
    paths:
      - build/*.deb
